module.exports = {
  "eh sukarra": "male_group",
  "la polla records": "male_group",
  "juan luis guerra 4.40": "mixed_group",
  "black eyed peas": "mixed_group",
  "calle 13": "mixed_group",
  "no doubt": "mixed_group",
  "toc": "male_group",
  "dupla": "male_group",
  "raimundo el canastero": "male_group",
  "ofenbach": "male_group",
  "omega": "male",
  "huntza": "mixed_group",
  "hofe": "male",
  "kiliki": "male",
  "nueve desconocidos": "male",
  "4:40": "mixed_group",
  "tatta": "male",
  "fane": "male",
  "denso": "male",
  "maida": "female",
  "etxepe": "male_group",
  "axeri": "male",
  "eli": "male",
  "feze": "male",
  "txiltxoko": "male_group",
  "figa flawas": "male_group",
  "la wera": "female",
  "bm": "male",
  "chris crone": "male",
  "cactus": "mixed_group",
  "castion": "male",
  "cali": "male",
  "el dandee": "male",
  "jart": "male",
  "d.basto": "male",
  "chill mafia records": "mixed_group",
  "chill mafia": "mixed_group",
  "erzin": "male",
  "seferolh": "male",
  "albany": "female",
  "lablackie": "female",
  "la txama": "male_group",
  "tatxers": "male_group",
  "tribade": "female_group",
  "irenen3s": "female",
  "plasaporros": "male_group",
  "the uski’s": "male_group",
  "the uski's": "male_group",
  "ben yart": "male",
  "lajoyeria": "male_group",
  "tuli bachatuli": "male",
  "tremenda jauría": "dissident_group",
  "la terrorista del sabor": "female",
  "leihotikan": "male_group",
  "el corazón del sapo": "male_group",
  "amygdala": "male",
  "errä": "male_group",
  "vato 18k": "male",
  "arene 6": "male_group",
  "zartako-k": "male_group",
  "los zopilotes txirriaos": "male_group",
  "kaleko urdangak": "male_group",
  "the lio": "male_group",
  "rotten xiii": "male_group",
  "jahgoikoa eta reggaezarra": "male_group",
  "kaparrak": "male_group",
  "añube": "male_group",
  "rip": "male_group",
  "ze esatek!": "male_group",
  "og gs": "male",
  "hemendik at": "mixed_group",
  "euskal bass": "male_group",
  "tximeleta": "mixed_group",
  "pipo beatz": "male",
  "virtual flavor": "male_group",
  "brigade loco": "male_group",
  "rico rosa": "male",
  "w sound": "male_group",
  "xules": "male",
  "hazas": "male",
  "zilibito records": "male_group",
  "uto": "male",
  "arbe": "male",
  "azk beats": "male",
  "txuso": "male",
  "toutz": "male",
  "mr.luken": "male",
  "merina gris": "mixed_group",
  "kaños": "male_group",
  "geckodelarue": "male",
  "monsieur lecrêpe": "male",
  "sunny wright iv": "male",
  "zecca": "male",
  "pam remixes": "male_group",
  "lendakaris muertos": "male_group",
  "txapelpunk": "male_group",
  "kortatu": "male_group",
  "piperrak": "male_group",
  "raffa fl": "male",
  "michaelbm": "male",
  "jayie": "female",
  "phil jay": "male",
  "porretas": "male_group",
  "skalariak": "male_group",
  "dodosound": "male",
  "xxirri": "male",
  "saim mendi": "male",
  "raperu": "male",
  "la raíz": "male_group",
  "zoo": "male_group",
  "gose": "mixed_group",
  "itaca band": "mixed_group",
  "xiberoots": "male_group",
  "kilimak": "mixed_group",
  "dover": "mixed_group",
  "mon dvy": "male",
  "bomba estéreo": "mixed_group",
  "savage": "male",
  "fly project": "male_group",
  "j warner": "male",
  "maki": "male",
  "italobrothers": "male_group",
  "rafaga": "male_group",
  "en tol sarmiento": "male_group",
  "grupo frontera": "male_group",
  "extremoduro": "male_group",
  "mora": "male",
  "bores d": "male",
  "pisoo": "male",
  "blacknife": "male_group",
  "efecto pasillo": "male_group",
  "bongo botrako": "male_group",
  "boikot": "male_group",
  "ciudad jara": "male_group",
  "aspencat": "male_group",
  "kaotiko": "male_group",
  "nena daconte": "female",
  "venezuela vence siempre": "male_group",
  "main costa": "male",
  "me fritos and the gimme cheetos": "male_group",
  "naxker": "male_group",
  "maruxak": "dissident_group",
  "chulería, joder!": "mixed_group",
  "joder!": "mixed_group",
  "labar": "male_group",
  "selecta": "male",
  "su hau dena": "mixed_group",
  "mirua": "mixed_group",
  "perlata": "female_group",
  "j martina": "mixed_group",
  "quinto": "male",
  "non servium": "male_group",
  "kaos urbano": "male_group",
  "radiocrimen": "male_group",
  "neomak": "female_group",
  "bulego": "male_group",
  "daniela garsal": "female",
  "maren": "female",
  "altxa lili": "female_group",
  "pirritx porrotx eta marimotots": "mixed_group",
  "nafarroa 1512": "male_group",
  "streetwise": "male_group",
  "eskorbuto": "male_group",
  "rotten amairu": "male_group",
  "kabasaki": "male",
  "gora etorri": "mixed_group",
  "ziztada": "mixed_group",
  "ladilla rusa": "mixed_group",
  "los ganglios": "mixed_group",
  "lady gipsy": "mixed_group",
  "la gossa sorda": "male_group",
  "la graciosa": "mixed_group",
  "al golpito": "mixed_group",
  "xiyo": "male",
  "fernandezz": "male",
  "pichi": "male",
  "acido folklórico": "male_group",
  "banda bassotti": "male_group",
  "sargentodmt": "male",
  "habeas corpus": "male_group",
  "auxili": "male_group",
  "skabidean": "mixed_group",
  "burutik": "mixed_group",
  "ya ice dilan": "male",
  "rey tony": "male",
  "helabusador": "male",
  "jipmusic global": "male",
  "fuego": "male",
  "nueva línea": "male_group",
  "ene": "male",
  "vilu gontero": "female",
  "julieta sw": "female",
  "julieta": "female",
  "came beats": "male",
  "sully riot": "male_group",
  "doctor fli": "male",
  "kreamly": "male",
  "atb norte": "male_group",
  "u r k": "male",
  "enlacrestaurbana": "male_group",
  "glorysixvain": "male",
  "mati guerra": "male",
  "paquillo castro": "male",
  "karapaixo": "male_group",
  "los buyer": "male_group",
  "pikeras": "male"
};
